"""Remove last_chat column from Contact

Revision ID: 096c6d80046d
Revises: 64f4b9b75788
Create Date: 2026-02-22 15:57:19.458324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096c6d80046d'
down_revision = '64f4b9b75788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_activity')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_participant_activity', ['participant_id', 'activity_id'])

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('deleted_history',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_unique_constraint('uq_owner_contact', ['owner_user_id', 'contact_user_id'])
        batch_op.drop_column('last_chat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_chat', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_owner_contact', type_='unique')
        batch_op.alter_column('deleted_history',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_participant_activity', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_activity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('time', sa.VARCHAR(length=10), nullable=True),
    sa.Column('duration_hours', sa.INTEGER(), nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=True),
    sa.Column('format_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('energy', sa.VARCHAR(length=10), nullable=True),
    sa.Column('participants', sa.INTEGER(), nullable=True),
    sa.Column('max_participants', sa.INTEGER(), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=200), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
