"""Add deleted_history column to Contact

Revision ID: 15dad30d91c7
Revises: 9840832b8296
Create Date: 2026-02-15 21:39:55.058623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dad30d91c7'
down_revision = '9840832b8296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_history', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('deleted_history')

    # ### end Alembic commands ###
