"""Add deleted_history column to Contact

Revision ID: 15dad30d91c7
Revises: 9840832b8296
Create Date: 2026-02-15 21:39:55.058623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dad30d91c7'
down_revision = '9840832b8296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
