"""Add guardian relationship to users

Revision ID: 1fc2e87450a5
Revises: 29b4e6cd0564
Create Date: 2026-02-11 17:46:05.322242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc2e87450a5'
down_revision = '29b4e6cd0564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=35),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=12),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_guardian_id', 'user', ['guardian_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('guardian_id')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=35),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
