"""Add chat_group and message_status to Contact

Revision ID: 29b4e6cd0564
Revises: 9e3ac5ded7d6
Create Date: 2026-01-19 14:09:17.276330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b4e6cd0564'
down_revision = '9e3ac5ded7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_group', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('chat_group')

    # ### end Alembic commands ###
