"""Remove last_chat column from Contact

Revision ID: 64f4b9b75788
Revises: 870ec6363af4
Create Date: 2026-02-22 15:52:06.716079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f4b9b75788'
down_revision = '870ec6363af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_participant_activity', ['participant_id', 'activity_id'])

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('deleted_history',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_unique_constraint('uq_owner_contact', ['owner_user_id', 'contact_user_id'])
        batch_op.drop_column('last_chat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_chat', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_owner_contact', type_='unique')
        batch_op.alter_column('deleted_history',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_participant_activity', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
