"""Add chat_cleared_at column to Contact

Revision ID: 870ec6363af4
Revises: 15dad30d91c7
Create Date: 2026-02-15 21:48:26.136821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870ec6363af4'
down_revision = '15dad30d91c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_cleared_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('chat_cleared_at')

    # ### end Alembic commands ###
