"""fix contact foreign key to user

Revision ID: 9840832b8296
Revises: f9b2b6c6a4d1
Create Date: 2026-02-15 12:15:03.800040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9840832b8296'
down_revision = 'f9b2b6c6a4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('contact_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('display_name', sa.String(length=35), nullable=False))
        batch_op.drop_constraint('uq_contact_phone', type_='unique')
        batch_op.create_foreign_key('fk_contact_owner_user_id', 'user', ['owner_user_id'], ['id'])
        batch_op.create_foreign_key('fk_contact_contact_user_id', 'user', ['contact_user_id'], ['id'])
        batch_op.drop_column('chat_group')
        batch_op.drop_column('phone')
        batch_op.drop_column('name')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_message_contact', type_='foreignkey')
        batch_op.create_foreign_key('fk_message_sender_id', 'user', ['sender_id'], ['id'])
        batch_op.create_foreign_key('fk_message_receiver_id', 'user', ['receiver_id'], ['id'])
        batch_op.drop_column('contact_id')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('contact_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_message_sender_id', type_='foreignkey')
        batch_op.drop_constraint('fk_message_receiver_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_message_contact', 'contact', ['contact_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=35), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=8), nullable=False))
        batch_op.add_column(sa.Column('chat_group', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_contact_owner_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_contact_contact_user_id', type_='foreignkey')
        batch_op.create_unique_constraint('uq_contact_phone', ['phone'])
        batch_op.drop_column('display_name')
        batch_op.drop_column('contact_user_id')
        batch_op.drop_column('owner_user_id')

    # ### end Alembic commands ###
