"""Fix timestamp default

Revision ID: b1ee26f24177
Revises: 1fc2e87450a5
Create Date: 2026-02-12 18:27:45.493204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ee26f24177'
down_revision = '1fc2e87450a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_guardian_id', type_='foreignkey')
        batch_op.drop_column('guardian_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_guardian_id', 'user', ['guardian_id'], ['id'])

    # ### end Alembic commands ###
