"""Rename email to short_desc in Contact

Revision ID: bc60552187a5
Revises: 4d1feb472288
Create Date: 2026-01-14 01:21:41.560462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc60552187a5'
down_revision = '4d1feb472288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_desc', sa.String(length=120), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('short_desc')

    # ### end Alembic commands ###
