"""add is_demo to groups

Revision ID: e46c997a57a3
Revises: e80c7fdc1c70
Create Date: 2026-02-14 05:14:53.206867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46c997a57a3'
down_revision = 'e80c7fdc1c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    # ### end Alembic commands ###
